OrdererOrgs:
  - Name: Orderer
    Domain: honeychain.local
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.honeychain.local
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
