OrdererOrgs:
  - Name: Orderer
    Domain: honeychain.local
    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"
          - "127.0.0.1"
          - "orderer.honeychain.local"

PeerOrgs:
  - Name: Org1
    Domain: org1.honeychain.local
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0
        SANS:
          - "localhost"
          - "127.0.0.1"
          - "peer0.org1.honeychain.local"
    Users:
      Count: 1
