-- Honey Chain PostgreSQL Database Schema

CREATE TABLE IF NOT EXISTS beekeepers (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact VARCHAR(255),
    location VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hives (
    id VARCHAR(64) PRIMARY KEY,
    beekeeper_id VARCHAR(64) REFERENCES beekeepers(id) ON DELETE SET NULL,
    location JSONB NOT NULL, -- { lat, lng, address }
    installation_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(32) DEFAULT 'ACTIVE', -- ACTIVE, INACTIVE, WARNING, CRITICAL
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS telemetry (
    id SERIAL PRIMARY KEY,
    hive_id VARCHAR(64) NOT NULL REFERENCES hives(id) ON DELETE CASCADE,
    temperature NUMERIC(5, 2) NOT NULL,
    humidity NUMERIC(5, 2) NOT NULL,
    weight NUMERIC(5, 2) NOT NULL,
    activity NUMERIC(3, 2) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_telemetry_hive_timestamp ON telemetry(hive_id, timestamp DESC);

CREATE TABLE IF NOT EXISTS harvests (
    id VARCHAR(64) PRIMARY KEY,
    hive_id VARCHAR(64) NOT NULL REFERENCES hives(id) ON DELETE CASCADE,
    beekeeper_id VARCHAR(64) REFERENCES beekeepers(id) ON DELETE SET NULL,
    harvest_date TIMESTAMP WITH TIME ZONE NOT NULL,
    quantity NUMERIC(6, 2) NOT NULL, -- in kg
    location JSONB,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS batches (
    id VARCHAR(64) PRIMARY KEY, -- e.g. HC-2026-0001
    harvest_id VARCHAR(64) REFERENCES harvests(id) ON DELETE SET NULL,
    quantity NUMERIC(6, 2) NOT NULL,
    origin VARCHAR(255) NOT NULL,
    status VARCHAR(32) DEFAULT 'CREATED', -- CREATED, PROCESSING, TRANSPORT, PACKAGED, VERIFIED, SUSPICIOUS
    blockchain_tx_id VARCHAR(128),
    blockchain_status VARCHAR(32) DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS processing_events (
    id VARCHAR(64) PRIMARY KEY,
    batch_id VARCHAR(64) NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
    processor_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    details JSONB,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transport_events (
    id VARCHAR(64) PRIMARY KEY,
    batch_id VARCHAR(64) NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
    transporter_id VARCHAR(64) NOT NULL,
    source VARCHAR(255) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS packaging_events (
    id VARCHAR(64) PRIMARY KEY,
    batch_id VARCHAR(64) NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
    packager_id VARCHAR(64) NOT NULL,
    product_id VARCHAR(64) NOT NULL,
    packaging_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS certifications (
    id VARCHAR(64) PRIMARY KEY,
    batch_id VARCHAR(64) NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
    authority VARCHAR(255) NOT NULL,
    certificate_type VARCHAR(128) NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(32) DEFAULT 'VALID'
);
